# Generated by Django 5.1.4 on 2025-02-17 23:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_country', models.CharField(max_length=100)),
                ('artist_bio', models.TextField(blank=True, null=True)),
                ('artist_image', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['artist_name'],
                'indexes': [models.Index(fields=['-created_at', 'artist_country'], name='event_info__created_9f3916_idx')],
            },
        ),
    ]
